import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./nav/page";
import { getUserFromLocalStorage } from "@/service/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const doesUserAuthorized = getUserFromLocalStorage;
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#f9fafb" }}>
        {!doesUserAuthorized && <Nav />}
        {children}
      </body>
    </html>
  );
}
